### ISSUE TITLE
Make LeftDrawer Responsive to Screen Size

### ISSUE THREAD

**Issue by codyswanner** [codyswanner/Meme-Cataloger#30]
LeftDrawer is currently hard-coded for consistent size and permanency.  For mobile, this size should be different from desktop, and ideally the drawer will hide until called for (probably with a hamburger button).

**Comment by hunxjunedo** [comment]
Assignment request, would like to contribute.

**Comment by codyswanner** [comment]
@hunxjunedo you are assigned, thanks for helping out!  Ping me here when the PR is ready, or if you need anything from me!

**Comment by hunxjunedo** [comment]
hey, I would really contribute to it but unfortunately I have no prior experience working with Django, therefore even though I tried, I couldn't properly setup the dev environment. So I might not be able to contribute to this, I'm still trying to set it up.

**Comment by codyswanner** [comment]
Ah, that makes sense.  You may be able to run the React part separately without Django, but I'm actually not sure.  I'm actually working right now on Dockerizing the whole thing, if I can get that working then I should be able to share the Docker files and that should get you up and running without having to mess with Django at all.  @hunxjunedo I'll keep you posted!

**Comment by codyswanner** [comment]
Addressed in #106
